reviews:
  auto_review:
    enabled: true

instructions:
  - "When reviewing Python files, suggest secure connection code using environment variables."
  - "Prefer parameterized queries and best practices."
